import { Group, Text, Anchor } from '@mantine/core';
import type { EpgIndex } from '../lib/xmltv/types';

export interface EpgHeaderInfoProps {
  index: EpgIndex;
}

export function EpgHeaderInfo({ index }: EpgHeaderInfoProps) {
  const { header, channels, totalProgrammeCount } = index;
  if (!header.generatorInfoName && !header.generatorInfoUrl && channels.count === 0) return null;

  return (
    <Group gap="xs" wrap="nowrap">
      {header.generatorInfoName && (
        <Text size="xs" c="dimmed" truncate>
          Generated by:{' '}
          {header.generatorInfoUrl ? (
            <Anchor href={header.generatorInfoUrl} target="_blank" rel="noopener noreferrer" size="xs">
              {header.generatorInfoName}
            </Anchor>
          ) : (
            header.generatorInfoName
          )}
        </Text>
      )}
      <Text size="xs" c="dimmed" style={{ whiteSpace: 'nowrap' }}>
        {channels.count.toLocaleString()} channels · {totalProgrammeCount.toLocaleString()} programmes
      </Text>
    </Group>
  );
}
