import { useEffect, useRef, useState } from 'react';
import { Group, Text, Anchor, Popover, ActionIcon } from '@mantine/core';
import { IconInfoCircle } from '@tabler/icons-react';
import type { EpgIndex } from '../lib/xmltv/types';

export interface EpgHeaderInfoProps {
  index: EpgIndex;
}

export function EpgHeaderInfo({ index }: EpgHeaderInfoProps) {
  const { header, channels, totalProgrammeCount } = index;
  const containerRef = useRef<HTMLDivElement | null>(null);
  const measureRef = useRef<HTMLSpanElement | null>(null);
  const [fitsFull, setFitsFull] = useState(true);
  const [infoOpen, setInfoOpen] = useState(false);

  // Measures a hidden, naturally-sized clone of the label against the
  // available space, re-checked on resize/rotation. Deliberately not
  // CSS text-overflow: ellipsis on the visible text — a dangling partial
  // string reads worse than just showing the (i) icon alone when there's
  // no room for the whole thing.
  useEffect(() => {
    const container = containerRef.current;
    const measure = measureRef.current;
    if (!container || !measure) return;
    const check = () => setFitsFull(measure.scrollWidth <= container.clientWidth);
    check();
    const observer = new ResizeObserver(check);
    observer.observe(container);
    return () => observer.disconnect();
  }, [header.generatorInfoName, header.generatorInfoUrl]);

  if (!header.generatorInfoName && !header.generatorInfoUrl && channels.count === 0) return null;

  const generatorLabel = (
    <>
      Generated by:{' '}
      {header.generatorInfoUrl ? (
        <Anchor href={header.generatorInfoUrl} target="_blank" rel="noopener noreferrer" size="xs">
          {header.generatorInfoName}
        </Anchor>
      ) : (
        header.generatorInfoName
      )}
    </>
  );

  return (
    <Group gap="xs" wrap="nowrap" justify="space-between" align="center" style={{ width: '100%', minWidth: 0 }}>
      {header.generatorInfoName ? (
        <div
          ref={containerRef}
          style={{
            position: 'relative',
            flex: '1 1 auto',
            minWidth: 0,
            overflow: 'hidden',
            display: 'flex',
            alignItems: 'center',
          }}
        >
          <span ref={measureRef} style={{ position: 'absolute', visibility: 'hidden', whiteSpace: 'nowrap', pointerEvents: 'none' }}>
            <Text component="span" size="xs">
              {generatorLabel}
            </Text>
          </span>
          {fitsFull ? (
            <Text size="xs" c="dimmed" style={{ whiteSpace: 'nowrap' }}>
              {generatorLabel}
            </Text>
          ) : (
            <Popover opened={infoOpen} onChange={setInfoOpen} withArrow position="top" width={280} shadow="md">
              <Popover.Target>
                <ActionIcon
                  variant="subtle"
                  color="gray"
                  size="sm"
                  style={{ color: 'var(--mantine-color-dimmed)' }}
                  onClick={() => setInfoOpen((o) => !o)}
                  aria-label="Show full generator info"
                >
                  <IconInfoCircle size={14} />
                </ActionIcon>
              </Popover.Target>
              <Popover.Dropdown>
                <Text size="xs">{generatorLabel}</Text>
              </Popover.Dropdown>
            </Popover>
          )}
        </div>
      ) : (
        <div />
      )}
      <Text size="xs" c="dimmed" style={{ whiteSpace: 'nowrap', flexShrink: 0 }}>
        {channels.count.toLocaleString()} channels · {totalProgrammeCount.toLocaleString()} programmes
      </Text>
    </Group>
  );
}
