import { Group, Text, Anchor } from '@mantine/core';
import type { EpgIndex } from '../lib/xmltv/types';

export interface EpgHeaderInfoProps {
  index: EpgIndex;
}

export function EpgHeaderInfo({ index }: EpgHeaderInfoProps) {
  const { header, channels, totalProgrammeCount } = index;
  if (!header.generatorInfoName && !header.generatorInfoUrl && channels.length === 0) return null;

  return (
    <Group gap="md" wrap="wrap">
      {header.generatorInfoName && (
        <Text size="sm" c="dimmed">
          Generated by:{' '}
          {header.generatorInfoUrl ? (
            <Anchor href={header.generatorInfoUrl} target="_blank" rel="noopener noreferrer" size="sm">
              {header.generatorInfoName}
            </Anchor>
          ) : (
            header.generatorInfoName
          )}
        </Text>
      )}
      <Text size="sm" c="dimmed">
        {channels.length.toLocaleString()} channels · {totalProgrammeCount.toLocaleString()} programmes
      </Text>
    </Group>
  );
}
